### PR TITLE
Allow for using tailored profiles from CaC

### PR DESCRIPTION
**Pull request by JAORMX**
This allows for specifying TailoredProfiles to use instead of the
profile directly. This is useful when trying to set variables in
profiles for testing.

The tailoring needs to exist in the `ocp-resources/tailorings` directory
in ComplianceAsCode/content. And it needs to have the following file
name:

    <product>-<profile name>.yaml

Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>

### CODE REVIEW

**Review by Vincent056 — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 78a3d3d638b3190488fd26ec6b73c44a578a9046

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 4f92d8c217a279ae2a4b302b3b87d86e93b8fdce

**Review by jhrozek — APPROVED** [review]
/lgtm

**Pull request merged**
